/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Backend.*;
import static Backend.Main.cetakMap;
import static Backend.Main.promosiMap;
import static Backend.Main.userMap;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Satriock
 */
public class AdminWindow extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindow
     */
    public AdminWindow() {
        initComponents();
    }

    public void loadMember() {
        DefaultTableModel tableMember = (DefaultTableModel) memberTable.getModel();

        for (Map.Entry<String, Pelanggan> entry : userMap.entrySet()) {
            String memberID = entry.getKey();
            Pelanggan pelanggan = entry.getValue();
            Object[] rowData = {memberID, pelanggan.getNamaAwal(), ((Member) pelanggan).getJoinDate(), pelanggan.getSaldo()};
            tableMember.addRow(rowData);
        }
    }

    public void loadGuest() {
        DefaultTableModel tableGuest = (DefaultTableModel) guestTable.getModel();

        for (Map.Entry<String, Pelanggan> entry : userMap.entrySet()) {
            String ID = entry.getKey();
            Pelanggan pelanggan = entry.getValue();
            Object[] rowData = {ID, pelanggan.getSaldo()};
            tableGuest.addRow(rowData);
        }
    }

    public void loadPromo() {
        DefaultTableModel tablePromo = (DefaultTableModel) promoTable.getModel();

        for (Map.Entry<String, Promosi> entry : promosiMap.entrySet()) {
            String kodePromo = entry.getKey();
            Promosi promo = entry.getValue();
            if (promo instanceof Cashback) {
                Object[] rowData = {kodePromo, ((Cashback) promo).getTanggalAwal(), ((Cashback) promo).getTanggalAkhir(), ((Cashback) promo).getPersenPotongan(), ((Cashback) promo).getMaksPotongan(), ((Cashback) promo).getMinPembelian()};
                tablePromo.addRow(rowData);
            }
            if (promo instanceof Diskon) {
                Object[] rowData = {kodePromo, ((Diskon) promo).getTanggalAwal(), ((Diskon) promo).getTanggalAkhir(), ((Diskon) promo).getPersenPotongan(), ((Diskon) promo).getMaksPotongan(), ((Diskon) promo).getMinPembelian()};
                tablePromo.addRow(rowData);
            }
            if (promo instanceof DiskonOngkir) {
                Object[] rowData = {kodePromo, ((DiskonOngkir) promo).getTanggalAwal(), ((DiskonOngkir) promo).getTanggalAkhir(), ((DiskonOngkir) promo).getPersenPotongan(), ((DiskonOngkir) promo).getMaksPotongan(), ((DiskonOngkir) promo).getMinPembelian()};
                tablePromo.addRow(rowData);
            }
        }
    }

    public void loadMenu() {
        DefaultTableModel tableMenu = (DefaultTableModel) menuTable.getModel();

        for (Map.Entry<String, Cetak> entry : cetakMap.entrySet()) {
            String IDMenu = entry.getKey();
            Cetak menu = entry.getValue();
            Object[] rowData = {IDMenu, menu.getNama(), menu.getHargaFinal()};
            tableMenu.addRow(rowData);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        namaMember = new javax.swing.JTextField();
        tanggalDaftarMember = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        simpanMember = new javax.swing.JButton();
        saldoMember = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        memberID = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        kembaliMember = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        saldoGuest = new javax.swing.JTextField();
        simpanGuest = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        guestID = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        guestTable = new javax.swing.JTable();
        kembaliGuest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        promoCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        simpanPromo = new javax.swing.JButton();
        tglAwal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tglAkhir = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        persenPotong = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        maxPotong = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        minBeli = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comboPromo = new javax.swing.JComboBox<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        promoTable = new javax.swing.JTable();
        kembaliPromo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        menuID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        simpanMenu = new javax.swing.JButton();
        comboMenu = new javax.swing.JComboBox<>();
        menuNama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hargaMenu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        kembaliMenu = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("ID");

        namaMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMemberActionPerformed(evt);
            }
        });

        tanggalDaftarMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalDaftarMemberActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Daftar");

        jLabel7.setText("Saldo");

        simpanMember.setText("Simpan");
        simpanMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMemberActionPerformed(evt);
            }
        });

        saldoMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoMemberActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama ");

        memberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberIDActionPerformed(evt);
            }
        });

        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Tanggal Daftar", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(memberTable);

        kembaliMember.setText("Kembali");
        kembaliMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanggalDaftarMember, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(memberID, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(saldoMember, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(kembaliMember)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(simpanMember)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalDaftarMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoMember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanMember)
                    .addComponent(kembaliMember))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Member", jPanel2);

        jLabel9.setText("ID");

        saldoGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoGuestActionPerformed(evt);
            }
        });

        simpanGuest.setText("Simpan");
        simpanGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanGuestActionPerformed(evt);
            }
        });

        jLabel10.setText("Saldo");

        guestID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestIDActionPerformed(evt);
            }
        });

        guestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(guestTable);

        kembaliGuest.setText("Kembali");
        kembaliGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guestID, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(saldoGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(kembaliGuest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpanGuest)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(saldoGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanGuest)
                    .addComponent(kembaliGuest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Guest", jPanel4);

        jLabel3.setText("Kode Promo");

        simpanPromo.setText("Simpan");
        simpanPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPromoActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal Awal");

        jLabel14.setText("Tanggal AKhir");

        jLabel15.setText("Persen Potongan");

        jLabel16.setText("Max Potongan");

        jLabel17.setText("Min Pembelian");

        comboPromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASHBACK", "DISKON", "DISKON ONGKIR" }));

        promoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Promo", "Tanggal Awal", "Tanggal Akhir", "Persen Potongan", "Maks Potongan", "Min Pembelian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane10.setViewportView(promoTable);

        kembaliPromo.setText("Kembali");
        kembaliPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliPromoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(kembaliPromo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxPotong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(persenPotong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanPromo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(promoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(comboPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promoCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persenPotong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxPotong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPromo)
                    .addComponent(kembaliPromo))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Promo", jPanel3);

        jLabel11.setText("ID Menu");

        simpanMenu.setText("Simpan");
        simpanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMenuActionPerformed(evt);
            }
        });

        comboMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOKUMEN", "FOTOKOPI" }));
        comboMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMenuActionPerformed(evt);
            }
        });

        jLabel12.setText("Nama Menu");

        jLabel13.setText("Harga");

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Menu", "Nama Menu", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(menuTable);

        kembaliMenu.setText("Kembali");
        kembaliMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuNama, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(kembaliMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpanMenu)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(comboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuNama, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanMenu)
                    .addComponent(kembaliMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Menu", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberIDActionPerformed

    private void saldoMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoMemberActionPerformed

    private void simpanMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMemberActionPerformed
        // TODO add your handling code here:
        String ID = memberID.getText();
        String nama = namaMember.getText();
        String tanggalDaftar = tanggalDaftarMember.getText();
        int saldoMember = Integer.parseInt(this.saldoMember.getText());
        Pelanggan member = new Member(ID, nama, tanggalDaftar, saldoMember);
        Main.userMap.put(ID, member);
        loadMember();
    }//GEN-LAST:event_simpanMemberActionPerformed

    private void tanggalDaftarMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalDaftarMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalDaftarMemberActionPerformed

    private void namaMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMemberActionPerformed

    private void saldoGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoGuestActionPerformed

    private void simpanGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanGuestActionPerformed
        // TODO add your handling code here:
        String ID = guestID.getText();
        int saldo = Integer.parseInt(saldoGuest.getText());
        Pelanggan guest = new Guest(ID, saldo);
        Main.userMap.put(ID, guest);
        loadGuest();
    }//GEN-LAST:event_simpanGuestActionPerformed

    private void guestIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestIDActionPerformed

    private void simpanPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPromoActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        try {
            if (comboPromo.getSelectedItem().toString().equals("CASHBACK")) {
                String kodePromo = promoCode.getText();
                LocalDate tanggalAwal = LocalDate.parse(tglAwal.getText(), formatter);
                LocalDate tanggalAkhir = LocalDate.parse(tglAkhir.getText(), formatter);
                double persenPotongan = Double.parseDouble(persenPotong.getText());
                int maksPotongan = Integer.parseInt(maxPotong.getText());
                int minPembelian = Integer.parseInt(minBeli.getText());
                Promosi promo = new Cashback(kodePromo, tanggalAwal, tanggalAkhir, persenPotongan, maksPotongan, minPembelian);
                Main.promosiMap.put(kodePromo, promo);
            }
            if (comboPromo.getSelectedItem().toString().equals("DISKON")) {
                String kodePromo = promoCode.getText();
                LocalDate tanggalAwal = LocalDate.parse(tglAwal.getText(), formatter);
                LocalDate tanggalAkhir = LocalDate.parse(tglAkhir.getText(), formatter);
                double persenPotongan = Double.parseDouble(persenPotong.getText());
                int maksPotongan = Integer.parseInt(maxPotong.getText());
                int minPembelian = Integer.parseInt(minBeli.getText());
                Promosi promo = new Diskon(kodePromo, tanggalAwal, tanggalAkhir, persenPotongan, maksPotongan, minPembelian);
                Main.promosiMap.put(kodePromo, promo);
            }
            if (comboPromo.getSelectedItem().toString().equals("DISKON ONGKIR")) {
                String kodePromo = promoCode.getText();
                LocalDate tanggalAwal = LocalDate.parse(tglAwal.getText(), formatter);
                LocalDate tanggalAkhir = LocalDate.parse(tglAkhir.getText(), formatter);
                double persenPotongan = Double.parseDouble(persenPotong.getText());
                int maksPotongan = Integer.parseInt(maxPotong.getText());
                int minPembelian = Integer.parseInt(minBeli.getText());
                Promosi promo = new DiskonOngkir(kodePromo, tanggalAwal, tanggalAkhir, persenPotongan, maksPotongan, minPembelian);
                Main.promosiMap.put(kodePromo, promo);
            }
            loadPromo();
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }

    }//GEN-LAST:event_simpanPromoActionPerformed

    private void simpanMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMenuActionPerformed
        // TODO add your handling code here:
        if (comboMenu.getSelectedItem().toString().equals("DOKUMEN")) {
            String IDMenu = menuID.getText();
            String namaMenu = menuNama.getText();
            int hargaFinal = Integer.parseInt(hargaMenu.getText());
            Cetak menu = new Dokumen(IDMenu, namaMenu, hargaFinal);
            Main.cetakMap.put(IDMenu, menu);
        }
        if (comboMenu.getSelectedItem().toString().equals("FOTOKOPI")) {
            String IDMenu = menuID.getText();
            String namaMenu = menuNama.getText();
            int hargaFinal = Integer.parseInt(hargaMenu.getText());
            Cetak menu = new Fotokopi(IDMenu, namaMenu, hargaFinal);
            Main.cetakMap.put(IDMenu, menu);
        }
        loadMenu();

    }//GEN-LAST:event_simpanMenuActionPerformed

    private void comboMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboMenuActionPerformed

    private void kembaliPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliPromoActionPerformed
        // TODO add your handling code here:
        dispose();
        MainWindow main = new MainWindow();
        main.setVisible(true);
    }//GEN-LAST:event_kembaliPromoActionPerformed

    private void kembaliMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliMemberActionPerformed
        // TODO add your handling code here:
        dispose();
        MainWindow main = new MainWindow();
        main.setVisible(true);
    }//GEN-LAST:event_kembaliMemberActionPerformed

    private void kembaliGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliGuestActionPerformed
        // TODO add your handling code here:
        dispose();
        MainWindow main = new MainWindow();
        main.setVisible(true);
    }//GEN-LAST:event_kembaliGuestActionPerformed

    private void kembaliMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        MainWindow main = new MainWindow();
        main.setVisible(true);
    }//GEN-LAST:event_kembaliMenuActionPerformed

    private void menuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboMenu;
    private javax.swing.JComboBox<String> comboPromo;
    private javax.swing.JTextField guestID;
    private javax.swing.JTable guestTable;
    private javax.swing.JTextField hargaMenu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton kembaliGuest;
    private javax.swing.JButton kembaliMember;
    private javax.swing.JButton kembaliMenu;
    private javax.swing.JButton kembaliPromo;
    private javax.swing.JTextField maxPotong;
    private javax.swing.JTextField memberID;
    private javax.swing.JTable memberTable;
    private javax.swing.JTextField menuID;
    private javax.swing.JTextField menuNama;
    private javax.swing.JTable menuTable;
    private javax.swing.JTextField minBeli;
    private javax.swing.JTextField namaMember;
    private javax.swing.JTextField persenPotong;
    private javax.swing.JTextField promoCode;
    private javax.swing.JTable promoTable;
    private javax.swing.JTextField saldoGuest;
    private javax.swing.JTextField saldoMember;
    private javax.swing.JButton simpanGuest;
    private javax.swing.JButton simpanMember;
    private javax.swing.JButton simpanMenu;
    private javax.swing.JButton simpanPromo;
    private javax.swing.JTextField tanggalDaftarMember;
    private javax.swing.JTextField tglAkhir;
    private javax.swing.JTextField tglAwal;
    // End of variables declaration//GEN-END:variables
}
